# Generated by Django 2.1.10 on 2019-09-09 14:19

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0006_postcontentpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcontentpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='postcontentpage',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(help_text='WYSIWYG text')), ('align', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center'), ('justify', 'Justify')]))])), ('blog', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(help_text='WYSIWYG text')), ('align', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center'), ('justify', 'Justify')]))]))]),
        ),
        migrations.DeleteModel(
            name='PostContentPage',
        ),
    ]
