# Generated by Django 2.1.10 on 2019-09-09 15:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190909_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontentpage',
            name='body',
            field=wagtail.core.fields.StreamField([('blog', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(help_text='WYSIWYG text')), ('align', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center'), ('justify', 'Justify')]))]))]),
        ),
    ]
